### ISSUE TITLE
Not able to run the app. MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by tmnrp** [FusionAuth/fusionauth-example-node#1]
Solved
Replaced "file..." to ""@fusionauth/node-client": "1.12.0","

-performed git clone
-npm i
-npm start
//Did i miss anything (prerequisites)

![image](https://user-images.githubusercontent.com/21990847/81934791-2a801600-960d-11ea-8844-ee09c7fac255.png)

**Comment by tmnrp** [comment]
Replaced "file..." to ""@fusionauth/node-client"

**Comment by robotdan** [comment]
@tmnrp  thanks for the issue. 

Is there a typo that we need to fix? @mooreds is this one of our managed examples, or is this one that needs to be archived?

**Comment by mooreds** [comment]
We should archive or update this project since the node client library is now deprecated in favor of the typescript library. https://fusionauth.io/docs/v1/tech/client-libraries/node

I will archive this project and make a note to create a new javascript example project.

**Comment by mooreds** [comment]
Actually @robotdan I don't have the permissions to archive this project. Can you please do so whenever is convenient?

**Comment by voidmain** [comment]
I created this project a few months back to use for the 5-minute Setup Guide. It should be quite simple to fix it up to use the new Typescript client, but I don't think we should archive it.

**Comment by mooreds** [comment]
Great, then I'll update it.

**Comment by mooreds** [comment]
Ran into some issues upgrading. See https://github.com/FusionAuth/fusionauth-typescript-client/issues/20 for more info.
